# Generated by Django 4.0.6 on 2022-11-09 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('login_id', models.CharField(default='B5F91E8966', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mob_no', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('slab', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='')),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.CharField(default='4D3D58576FAF405', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=30)),
                ('mob_no', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('package_GB', models.CharField(max_length=10)),
                ('package_MB', models.CharField(max_length=10)),
                ('package_duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('login_id', models.CharField(default='AD464E6346', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('staffname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='StateRto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModelName',
            fields=[
                ('id', models.CharField(default='B06DC3', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMakeBy',
            fields=[
                ('id', models.CharField(default='1A51F8', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.CharField(default='E18C3D', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_id', models.CharField(default='A805A19B68464ED', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(default='user', max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bima_policy.agents')),
                ('profile_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
                ('staf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bima_policy.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('slab_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.CharField(default='8D242C', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('mob_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('GSTIN', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='rtotable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rto_id', models.IntegerField()),
                ('RegNo', models.CharField(max_length=200)),
                ('sid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.staterto')),
            ],
        ),
        migrations.CreateModel(
            name='RtoConversionModel',
            fields=[
                ('id', models.CharField(default='ADC703', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('rto_series', models.CharField(max_length=10)),
                ('rto_return', models.CharField(max_length=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyid', models.CharField(default='3A11626', editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('policy_no', models.CharField(max_length=50, unique=True)),
                ('registration_no', models.CharField(max_length=50)),
                ('casetype', models.CharField(max_length=100)),
                ('insurance_comp', models.CharField(max_length=100)),
                ('sp_name', models.CharField(max_length=100)),
                ('sp_brokercode', models.CharField(max_length=100)),
                ('issueDate', models.DateField()),
                ('riskDate', models.DateField()),
                ('CPA', models.CharField(max_length=100)),
                ('insurance', models.FileField(upload_to='media/documents/')),
                ('previous_policy', models.FileField(null=True, upload_to='media/documents/')),
                ('vehicle_rc', models.FileField(null=True, upload_to='media/documents/')),
                ('customer_name', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('OD_premium', models.IntegerField()),
                ('TP_premium', models.IntegerField()),
                ('net', models.IntegerField()),
                ('GST', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=100)),
                ('policy_type', models.CharField(max_length=100)),
                ('vehicle_makeby', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_category', models.CharField(max_length=50)),
                ('other_info', models.CharField(max_length=50)),
                ('vehicle_fuel_type', models.CharField(max_length=50)),
                ('manufature_year', models.IntegerField()),
                ('engine_no', models.CharField(max_length=50)),
                ('chasis_no', models.CharField(max_length=50)),
                ('rewards_on', models.CharField(max_length=50)),
                ('rewards_age', models.IntegerField()),
                ('self_rewards_on', models.CharField(max_length=50)),
                ('self_rewards_age', models.IntegerField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('payoutid', models.CharField(default='3026ADD', editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('payout_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('vehicle_category', models.CharField(max_length=50)),
                ('policy_provider', models.CharField(max_length=50)),
                ('Insurance_company', models.CharField(max_length=50)),
                ('vehicle_make_by', models.CharField(max_length=50)),
                ('rto', models.CharField(max_length=50)),
                ('case_type', models.CharField(max_length=100)),
                ('coverage', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('cpa', models.CharField(max_length=50)),
                ('rewards_on', models.CharField(max_length=50)),
                ('rewards_age', models.IntegerField()),
                ('self_rewards_on', models.CharField(max_length=50)),
                ('self_rewards_age', models.IntegerField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
                ('slab_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.slab')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.CharField(default='D788FC', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('comp_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerCode',
            fields=[
                ('id', models.CharField(default='B0C0EE', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.CharField(default='D95D15', editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('beneficiary_name', models.CharField(max_length=50)),
                ('acc_no', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=50)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
        migrations.AddField(
            model_name='agents',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel'),
        ),
        migrations.CreateModel(
            name='InsuranceUpload',
            fields=[
                ('policyid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bima_policy.policy', verbose_name='policyid')),
                ('ins_upload', models.FileField(upload_to='media/documents/')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bima_policy.profilemodel')),
            ],
        ),
    ]
